name: "Terraform Setup"
description: "Reusable steps for Terraform workflows"
inputs:
  working-directory:
    description: "The directory where Terraform files are located"
    required: true
  aws-access-key-id:
    description: "AWS Access Key ID"
    required: true
  aws-secret-access-key:
    description: "AWS Secret Access Key"
    required: true

runs:
  using: "composite"
  steps:
    - uses: aws-actions/configure-aws-credentials@v4.1.0
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: us-east-1

    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.12.2"

    - name: terraform-init
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: terraform init
