name: Deploy via Terraform

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  terraform-check:
    runs-on: ubuntu-latest
    environment: run

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/terraform-setup
        with:
          working-directory: ./environments/dev
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - run: terraform fmt -check
        working-directory: ./environments/dev


  terraform-plan:
    runs-on: ubuntu-latest
    environment: run

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/terraform-setup
        with:
          working-directory: ./environments/dev
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - run: terraform plan
        working-directory: ./environments/dev


  terraform-apply:
    runs-on: ubuntu-latest
    environment: run

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/terraform-setup
        with:
          working-directory: ./environments/dev
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - run: terraform apply -auto-approve -lock-timeout=60s
        working-directory: ./environments/dev
